pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - check-success=tests (ubuntu-latest)
      - author=nix-direnv-bot
    actions:
      merge:
        method: merge
      delete_head_branch: {}
