queue_rules:
  - name: default
    merge_conditions:
      - check-success=Evaluate flake.nix
      - check-success=check lint [x86_64-linux]
      - check-success=devShell default [x86_64-linux]
      - check-success=lockfile
      - check-success=package default [x86_64-linux]
      - check-success=package test-runner-stable [x86_64-linux]
      - check-success=package test-runner-unstable [x86_64-linux]
      - check-success=tests (ubuntu-latest, stable)
      - check-success=tests (ubuntu-latest, unstable)
defaults:
  actions:
    queue:
      allow_merging_configuration_change: true
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - label=merge-queue
    actions:
      queue: {}
