queue_rules:
  - name: default
    merge_conditions:
      - check-success=buildbot/nix-eval
      - check-success=tests (ubuntu-latest, stable)
      - check-success=tests (ubuntu-latest, unstable)
defaults:
  actions:
    queue:
      allow_merging_configuration_change: true
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=master
      - label~=merge-queue|dependencies
    actions:
      queue: {}
