name: "Test"
on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        # FIXME macos garbage currently collect also nix-shell that runs the test
        #os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        extra_nix_config: |
          keep-outputs = true
          keep-derivations = true
          experimental-features = nix-command flakes
    - run:
        nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz ci.nix --run 'true'
